// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaktarKezelo.Core;

#nullable disable

namespace RaktarKezelo.Core.Migrations
{
    [DbContext(typeof(RaktarContext))]
    [Migration("20260502190139_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RaktarKezelo.Core.Entities.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriak");
                });

            modelBuilder.Entity("RaktarKezelo.Core.Entities.Termek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cikkszam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Keszlet")
                        .HasColumnType("int");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("MinKeszlet")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Termekek");
                });

            modelBuilder.Entity("RaktarKezelo.Core.Entities.Tranzakcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mennyiseg")
                        .HasColumnType("int");

                    b.Property<int>("TermekId")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TermekId");

                    b.ToTable("Tranzakciok");
                });

            modelBuilder.Entity("RaktarKezelo.Core.Entities.Termek", b =>
                {
                    b.HasOne("RaktarKezelo.Core.Entities.Kategoria", "Kategoria")
                        .WithMany("Termekek")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("RaktarKezelo.Core.Entities.Tranzakcio", b =>
                {
                    b.HasOne("RaktarKezelo.Core.Entities.Termek", "Termek")
                        .WithMany()
                        .HasForeignKey("TermekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Termek");
                });

            modelBuilder.Entity("RaktarKezelo.Core.Entities.Kategoria", b =>
                {
                    b.Navigation("Termekek");
                });
#pragma warning restore 612, 618
        }
    }
}
